"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/Main.py']
DATA_FILES = ['src/logging.conf',
			('',['src/app']),
			('',['src/controller']),
			('',['src/model']),
			('',['src/view'])
		]
OPTIONS = {
	'argv_emulation': True,
}

setup(
	name="Mongo-pyqt",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
